### ISSUE TITLE
DB:: inclusion?

### ISSUE THREAD

**Issue by torrobinson** [Lykegenes/laravel-5-snippets#14]
Hello,

It'd be nice to have DB:: (https://laravel.com/docs/5.0/database) added.

Thanks!

**Comment by johnnymn** [comment]
+1

**Comment by patricksamson** [comment]
Not sure how to integrate Fluent queries yet, but I`m on it!

**Comment by patricksamson** [comment]
I added some basic snippets in commit 31956c3 and version 1.2.8.

I will not add snippets for Fluent queries because they will end up being too complex to be useful.
I mean, Snippets won't help for this : 

``` php
DB::table('users')
            ->where('name', '=', 'John')
            ->orWhere(function ($query) {
                $query->where('votes', '>', 100)
                      ->where('title', '<>', 'Admin');
            })
            ->get();
```

**Comment by torrobinson** [comment]
Thanks!
